---

site_name: Tech notes

theme:
  name: material

nav:
  - Home: index.md
  - E-mail: email.md
  - Linix commands: linux_commands.md
  - Nginx: nginx.md
  - Proxmox: proxmox.md
  - Wireguard: wireguard.md
